### PR TITLE
#158520925 Add  GET /api/v1/rides/{ride_id}  api End-point

### PR DESCRIPTION
**Pull request by meshack-mbuvi**
**What does this PR do?
Adds endpoint to retrieve a single ride offer

**Description of Task to be completed?**
- Create an `GET /api/v1/rides/{ride_id}` endpoint to retrieve a ride offer depending on the supplied `ride_id`
- Document this new endpoint on README.md

**How should this be manually tested?**
- Clone this repository
- In your terminal, cd ride-my-way-api
- `git checkout ft-retrieve-a-ride-158520925
- Activate virtual environment and install the dependencies
- Execute `python3 run.py`
- Using 'Postman', point to 'your-server:5000/api/v1/rides/{ride_id}` 

**What are the relevant pivotal tracker stories?**
[#158520925](https://www.pivotaltracker.com/story/show/158520925)

**Screenshots**
single ride

### CODE REVIEW

**Comment by Xerrex** [comment]
Nice.

**Comment by Xerrex** [comment]
Are you using An extension?

**Comment by meshack-mbuvi** [comment]
@Xerrex Extension as how?

**Comment by meshack-mbuvi** [comment]
Point noted very well

**Pull request merged**
